### ISSUE TITLE
Classification category

### ISSUE THREAD

**Issue by yuanbanlin** [ziyujia/ECML-PKDD_MMCNN#3]
Thank you for your open source work！ Do you do two classifications in both data sets? There are four classifications in bci2a data. Why don't you try to do four classifications？

**Comment by yuanbanlin** [comment]
I ran your original code, but the accuracy is only about 50% under the standard of default parameters (bci2b)

**Comment by ziyujia** [comment]
> Thank you for your open source work！ Do you do two classifications in both data sets? There are four classifications in bci2a data. Why don't you try to do four classifications？

We use binary classification in all datasets. In this work, we focus on two classifications: left and right. For a fair comparison, the baseline method is implemented also for a 2-classification task.

**Comment by ziyujia** [comment]
> I ran your original code, but the accuracy is only about 50% under the standard of default parameters (bci2b)

For binary classification tasks, 50% accuracy is equal to random classification. In fact, the initial parameter tuning of the proposed model is carried out on bci2b. And the result should be very stable. Please check your data processing, environment configuration and other content for yourself.

**Comment by yuanbanlin** [comment]
Thank you for your answer. Another question is why when I use a dataset, the data shape is (x, 1000, 3), and isn't the channel of raw data EEG 22
